language: ruby
rvm:
  - 2.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
install:
  - bundle install
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-html
  - bundle exec scss-lint ./_sass/**/*.scss
